name: vorun
description: A library for creating and managing runtime-validated value objects in Dart.
version: 0.0.1
homepage: https://github.com/ricardoboss/vorun

environment:
  sdk: '>=3.0.3 <4.0.0'

dev_dependencies:
  test: ^1.24.3
